language: python

sudo: false

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO=111
  - DJANGO=22
  - DJANGO=30

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=22
    - python: "2.7"
      env: DJANGO=30

install:
  - pip install tox coveralls

script:
  - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-dj$DJANGO

after_success:
  - coveralls

notifications:
    email:
        recipients:
            - dmkoch@gmail.com
